package LOOT;

public enum State {
    DYING,
    DEAD,
    REVIVED,
    TRAVELINGTOBANKCHEST,
    ATBANKCHEST,
    HASTELEPORT,
    ATVARROCK,
    TRAVELINGTOGRANDEXCHANGE,
    ATBANKPROMPT,
    ATGRANDEXCHANGE,
    WAITFORPLAYERDEATH,
    WALKINGTOPLAYERDEATH,
    WAITINGFORLOOT,
    CHECKINGLOOT,
    BANKITEMS
}
